- name: Install Apache Tomcat for Java Servlets on Ubuntu
  hosts: localhost
  become: yes
  tasks:
   - name: Update apt package cache
     apt:
       update_cache: yes
   - name: Install Java
     apt:
       name: openjdk-11-jdk
       state: present
   - name: Install unzip
     apt:
       name: unzip
       state: present
   - name: Download Apache Tomcat
     get_url:
       url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.87/bin/apache-tomcat-9.0.87.tar.gz"
       dest: "/tmp/apache-tomcat-9.0.87.tar.gz"
   - name: Extract Apache Tomcat archive
     ansible.builtin.unarchive:
       src: "/tmp/apache-tomcat-9.0.87.tar.gz"
       dest: "/opt"
       remote_src: yes
       creates: "/opt/apache-tomcat-9.0.87"
   - name: Start Apache Tomcat
     command: "/opt/apache-tomcat-9.0.87/bin/startup.sh"
